version: '3.5'

services:
  postgres:
    image: postgres:16
    container_name: java-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      #POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: workers
    ports:
      - "5432:5432"